import React from 'react';
import Head from 'next/head';
import styles from "./Layout.module.css";
import Navbar from "../navbar/Navbar";
import Footer from '../footer/Footer';


const Layout = ({children}) => {
  return (
    <div>
        <Head>
          <title>BrickWire Construction</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/brickLogo.ico" />
        </Head>
        <div>
          <Navbar />
              {children}
          <div className={styles.footer}><Footer /></div>
        </div>
    </div>
  )
}

export default Layout;